Document: ergo-telescope
Title: Debian ergo-telescope Manual
Author: <insert document author here>
Abstract: This manual describes what ergo-telescope is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ergo-telescope/ergo-telescope.sgml.gz

Format: postscript
Files: /usr/share/doc/ergo-telescope/ergo-telescope.ps.gz

Format: text
Files: /usr/share/doc/ergo-telescope/ergo-telescope.text.gz

Format: HTML
Index: /usr/share/doc/ergo-telescope/html/index.html
Files: /usr/share/doc/ergo-telescope/html/*.html
